[frontend]
routepilot-frontend ansible_host=10.100.1.10

[backend]
routepilot-backend ansible_host=10.100.2.10

[database]
routepilot-database ansible_host=10.100.3.10

[routepilot:children]
frontend
backend
database

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3