---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Prometheus Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Ensure Node Exporter is enabled and running
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started