name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend build
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/routepilot_ci

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci

      - name: Validate Prisma schema
        run: npm run prisma:validate

      - name: Generate Prisma client
        run: npm run prisma:generate

      - name: Build backend
        run: npm run build

  frontend:
    name: Frontend build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build


  publish-images:
    name: Publish Docker images
    runs-on: ubuntu-latest

    needs:
      - backend
      - frontend

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/nadaaath/routepilot-backend:latest
            ghcr.io/nadaaath/routepilot-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          build-args: |
            VITE_API_BASE_URL=/api
          tags: |
            ghcr.io/nadaaath/routepilot-frontend:latest
            ghcr.io/nadaaath/routepilot-frontend:${{ github.sha }}
